spring:
    autoconfigure:
      exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
        - "*" # turn off securing the actuator endpoints
        
logging:
  level:
    spring:
     cloud: info
  
greeting:
  displayFortune: true # <----Change to true
  
quoteServiceURL: https://quote-service-dev-12345.cfapps.io/quote
